CREATE TABLE IF NOT EXISTS `model_versions` (`id` text PRIMARY KEY NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`commit_sha` text NOT NULL,`status` text DEFAULT 'draft' NOT NULL,`graph_json` text DEFAULT '{"nodes":[],"edges":[]}' NOT NULL,`confidence` integer DEFAULT 0 NOT NULL,`scan_version` text DEFAULT 'wm-ts-1' NOT NULL,`user_overrides_json` text DEFAULT '{}' NOT NULL,`approved_by` text,`approved_at` text,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `model_versions_project_idx` ON `model_versions` (`workspace_id`,`project_id`,`created_at`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `repository_scans` (`id` text PRIMARY KEY NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`repository` text NOT NULL,`branch` text NOT NULL,`status` text DEFAULT 'queued' NOT NULL,`workflow_id` text,`commit_sha` text,`result_json` text,`error_code` text,`created_by` text NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `environment_revisions` (`id` text PRIMARY KEY NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`model_version_id` text NOT NULL,`backend` text NOT NULL,`status` text DEFAULT 'draft' NOT NULL,`manifest_json` text NOT NULL,`validation_json` text DEFAULT '{}' NOT NULL,`approved_by` text,`approved_at` text,`snapshot_ref` text,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `user_journeys` (`id` text PRIMARY KEY NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`status` text DEFAULT 'draft' NOT NULL,`source` text DEFAULT 'user' NOT NULL,`definition_json` text NOT NULL,`generated_diff` text,`approved_by` text,`approved_at` text,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `agent_conversations` (`id` text PRIMARY KEY NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`title` text NOT NULL,`openai_response_id` text,`created_by` text NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `agent_messages` (`id` text PRIMARY KEY NOT NULL,`conversation_id` text NOT NULL,`workspace_id` text NOT NULL,`role` text NOT NULL,`content` text NOT NULL,`structured_json` text,`model` text,`response_id` text,`usage_json` text,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `agent_runs` (`id` text PRIMARY KEY NOT NULL,`conversation_id` text NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`agent_kind` text NOT NULL,`model` text NOT NULL,`response_id` text NOT NULL,`prompt_version` text NOT NULL,`status` text NOT NULL,`usage_json` text DEFAULT '{}' NOT NULL,`approval_json` text DEFAULT '{}' NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `agent_tool_calls` (`id` text PRIMARY KEY NOT NULL,`agent_run_id` text NOT NULL,`workspace_id` text NOT NULL,`provider_call_id` text NOT NULL,`tool_name` text NOT NULL,`arguments_json` text NOT NULL,`validation_status` text NOT NULL,`result_ref` text,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `campaigns` (`id` text PRIMARY KEY NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`conversation_id` text,`name` text NOT NULL,`objective` text NOT NULL,`status` text DEFAULT 'draft' NOT NULL,`plan_json` text NOT NULL,`estimated_minutes` integer NOT NULL,`concurrency` integer NOT NULL,`approved_by` text,`approved_at` text,`workflow_id` text,`cancellation_requested_at` text,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `campaign_runs` (`id` text PRIMARY KEY NOT NULL,`campaign_id` text NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`scenario_index` integer NOT NULL,`scenario_json` text NOT NULL,`status` text DEFAULT 'queued' NOT NULL,`simulation_run_id` text,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `runner_callbacks` (`run_id` text PRIMARY KEY NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`token_jti` text NOT NULL UNIQUE,`evidence_json` text NOT NULL,`received_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `run_events` (`id` text PRIMARY KEY NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`run_id` text NOT NULL,`sequence` integer NOT NULL,`type` text NOT NULL,`source` text NOT NULL,`service_id` text,`journey_id` text,`payload_json` text DEFAULT '{}' NOT NULL,`evidence_ref` text,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `run_events_sequence_idx` ON `run_events` (`run_id`,`sequence`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `evidence_artifacts` (`id` text PRIMARY KEY NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`run_id` text,`kind` text NOT NULL,`r2_key` text NOT NULL,`sha256` text NOT NULL,`size_bytes` integer NOT NULL,`redacted` integer DEFAULT 1 NOT NULL,`expires_at` text,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `investigations` (`id` text PRIMARY KEY NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`run_id` text NOT NULL,`status` text DEFAULT 'queued' NOT NULL,`objective` text NOT NULL,`hypothesis_json` text,`workflow_id` text,`created_by` text NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `patch_candidates` (`id` text PRIMARY KEY NOT NULL,`investigation_id` text NOT NULL,`workspace_id` text NOT NULL,`strategy` text NOT NULL,`status` text DEFAULT 'queued' NOT NULL,`patch_ref` text,`changed_files_json` text DEFAULT '[]' NOT NULL,`tests_json` text DEFAULT '[]' NOT NULL,`gates_json` text DEFAULT '{}' NOT NULL,`metrics_json` text DEFAULT '{}' NOT NULL,`score` integer,`risks_json` text DEFAULT '[]' NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `verification_runs` (`id` text PRIMARY KEY NOT NULL,`candidate_id` text NOT NULL,`workspace_id` text NOT NULL,`scenario_fingerprint` text NOT NULL,`seed` text NOT NULL,`status` text NOT NULL,`metrics_json` text DEFAULT '{}' NOT NULL,`gates_json` text DEFAULT '{}' NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `decision_reports` (`id` text PRIMARY KEY NOT NULL,`workspace_id` text NOT NULL,`project_id` text NOT NULL,`run_id` text NOT NULL,`candidate_id` text,`status` text DEFAULT 'draft' NOT NULL,`report_json` text NOT NULL,`artifact_ref` text,`share_token_hash` text,`visibility` text DEFAULT 'private' NOT NULL,`published_at` text,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `report_approvals` (`report_id` text PRIMARY KEY NOT NULL,`workspace_id` text NOT NULL,`approved_by` text NOT NULL,`approved_at` text NOT NULL,`decision_note` text NOT NULL,`pr_status` text DEFAULT 'not_requested' NOT NULL,`pr_url` text,`pr_number` integer,`published_at` text);--> statement-breakpoint
