"use client";

import { useEffect, useMemo, useState } from "react";

type ScenarioKey = "traffic" | "database" | "payments";
type RunPhase = "ready" | "running" | "failed" | "repairing" | "repaired" | "verified";

const scenarios = {
  traffic: {
    label: "Traffic spike",
    detail: "20× load · 2m duration",
    event: "20× traffic ramp started",
    target: "API Gateway",
    baseline: { score: 42, errors: "18.7%", latency: "2.84s", journey: "61%" },
    after: { score: 91, errors: "0.8%", latency: "612ms", journey: "99%" },
  },
  database: {
    label: "Database slowdown",
    detail: "+800ms · orders-db",
    event: "800ms latency injected",
    target: "Orders DB",
    baseline: { score: 38, errors: "21.4%", latency: "3.19s", journey: "54%" },
    after: { score: 88, errors: "1.2%", latency: "734ms", journey: "98%" },
  },
  payments: {
    label: "Payment outage",
    detail: "503s · 45s window",
    event: "Payment provider returning 503",
    target: "Stripe API",
    baseline: { score: 31, errors: "32.1%", latency: "4.06s", journey: "22%" },
    after: { score: 94, errors: "0.4%", latency: "488ms", journey: "100%" },
  },
} as const;

const nodes = [
  { id: "storefront", label: "Storefront", kind: "Next.js", x: 10, y: 42, file: "apps/web/app/checkout/page.tsx" },
  { id: "gateway", label: "API Gateway", kind: "Fastify", x: 31, y: 42, file: "apps/api/src/server.ts" },
  { id: "checkout", label: "Checkout", kind: "Service", x: 52, y: 20, file: "services/checkout/src/index.ts" },
  { id: "orders", label: "Orders", kind: "Service", x: 52, y: 66, file: "services/orders/src/create.ts" },
  { id: "stripe", label: "Stripe API", kind: "External", x: 78, y: 12, file: "services/checkout/src/payment.ts" },
  { id: "database", label: "Orders DB", kind: "Postgres", x: 78, y: 62, file: "infra/docker-compose.yml" },
  { id: "email", label: "Email", kind: "Worker", x: 78, y: 82, file: "workers/email/src/consumer.ts" },
];

const journeySteps = ["Open store", "Add item", "View cart", "Submit payment", "Create order", "Confirmation"];

function Logo() {
  return <span className="logo-mark" aria-hidden="true"><i /><i /><i /></span>;
}

export default function Home() {
  const [scenario, setScenario] = useState<ScenarioKey>("payments");
  const [phase, setPhase] = useState<RunPhase>("ready");
  const [selectedNode, setSelectedNode] = useState("checkout");
  const [elapsed, setElapsed] = useState(0);
  const [showReport, setShowReport] = useState(false);
  const [showPr, setShowPr] = useState(false);
  const data = scenarios[scenario];

  const graphState = phase === "ready" ? "healthy" : phase === "verified" || phase === "repaired" ? "repaired" : "failed";
  const activeMetrics = phase === "verified" || phase === "repaired" ? data.after : data.baseline;

  useEffect(() => {
    if (phase !== "running") return;
    const ticker = window.setInterval(() => setElapsed((n) => Math.min(n + 5, 45)), 115);
    const done = window.setTimeout(() => setPhase("failed"), 1200);
    return () => { window.clearInterval(ticker); window.clearTimeout(done); };
  }, [phase]);

  const runScenario = () => { setElapsed(0); setPhase("running"); };
  const startRepair = () => {
    setPhase("repairing");
    window.setTimeout(() => setPhase("repaired"), 1400);
  };
  const verify = () => {
    setElapsed(0);
    setPhase("running");
    window.setTimeout(() => setPhase("verified"), 1250);
  };

  const selected = useMemo(() => nodes.find((n) => n.id === selectedNode)!, [selectedNode]);
  const isBroken = (id: string) => graphState === "failed" && ["checkout", "orders", scenario === "payments" ? "stripe" : scenario === "database" ? "database" : "gateway"].includes(id);

  const downloadReport = () => {
    const report = `WORLDMODEL VERIFICATION REPORT\n\nProject: shopstream/demo-store\nScenario: ${data.label} (${data.detail})\nScenario ID: scn_checkout_20x_8f31\nSeed: worldmodel-2026-0713\n\nROOT CAUSE\nUnbounded synchronous payment calls held checkout workers until timeout, propagating saturation to order creation and the checkout journey.\n\nVERIFIED REPAIR\nAdded a 1.5s timeout, circuit breaker, idempotency key, and durable payment-retry queue.\n\nBEFORE → AFTER\nResilience: ${data.baseline.score} → ${data.after.score}\nError rate: ${data.baseline.errors} → ${data.after.errors}\nP95 latency: ${data.baseline.latency} → ${data.after.latency}\nJourney success: ${data.baseline.journey} → ${data.after.journey}\n\nEVIDENCE\n✓ Identical scenario definition and random seed\n✓ 6/6 Playwright journey steps passed\n✓ 48 unit and integration checks passed\n✓ Order integrity preserved; zero duplicate orders\n\nDraft PR: feat/resilient-checkout (demo PR #248)\nGenerated by WorldModel for Software`;
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "worldmodel-verification-report.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <main className="app-shell">
      <header className="topbar">
        <div className="brand"><Logo /><span>WorldModel</span><b>ALPHA</b></div>
        <nav aria-label="Primary navigation"><button className="active">Twin</button><button>Runs</button><button>Reports</button></nav>
        <div className="repo-chip"><span className="repo-glyph">⌘</span><div><b>shopstream / demo-store</b><small>main · connected</small></div><span className="live-dot" /></div>
      </header>

      <section className="commandbar">
        <div>
          <span className="eyebrow">SOFTWARE TWIN</span>
          <h1>Checkout resilience <span>v24</span></h1>
        </div>
        <div className="command-actions">
          <span className="environment"><i /> Virtual environment ready</span>
          <button className="secondary" onClick={() => { setPhase("ready"); setScenario("payments"); }}>Reset demo</button>
          <button className="primary" data-testid="run-simulation" onClick={runScenario} disabled={phase === "running" || phase === "repairing"}>{phase === "running" ? "Running…" : "Run simulation"}<span>▶</span></button>
        </div>
      </section>

      <section className="metric-strip" aria-label="Run metrics">
        <div><span>RESILIENCE SCORE</span><strong className={graphState === "failed" ? "bad" : graphState === "repaired" ? "good" : ""}>{phase === "ready" ? "96" : activeMetrics.score}<small>/100</small></strong><em>{graphState === "failed" ? "−65 under fault" : phase === "verified" ? "+63 verified" : phase === "repaired" ? "candidate ready" : "healthy baseline"}</em></div>
        <div><span>ERROR RATE</span><strong>{phase === "ready" ? "0.2%" : activeMetrics.errors}</strong><em>{graphState === "failed" ? "threshold 2%" : "within threshold"}</em></div>
        <div><span>P95 LATENCY</span><strong>{phase === "ready" ? "342ms" : activeMetrics.latency}</strong><em>{graphState === "failed" ? "SLO 800ms" : "SLO passed"}</em></div>
        <div><span>JOURNEY SUCCESS</span><strong>{phase === "ready" ? "100%" : activeMetrics.journey}</strong><em>{graphState === "failed" ? "checkout blocked" : "6 of 6 steps"}</em></div>
        <div><span>SERVICES</span><strong>{graphState === "failed" ? "4 / 7" : "7 / 7"}</strong><em>{graphState === "failed" ? "3 degraded" : "all healthy"}</em></div>
      </section>

      <div className="workspace-grid">
        <aside className="scenario-panel panel">
          <div className="panel-heading"><span>SCENARIOS</span><button aria-label="Add scenario">＋</button></div>
          <div className="scenario-list">
            {(Object.keys(scenarios) as ScenarioKey[]).map((key) => (
              <button key={key} className={scenario === key ? "selected" : ""} onClick={() => { setScenario(key); setPhase("ready"); }}>
                <i className={`scenario-icon ${key}`}>{key === "traffic" ? "↗" : key === "database" ? "▤" : "⚡"}</i>
                <span><b>{scenarios[key].label}</b><small>{scenarios[key].detail}</small></span>
                {scenario === key && <em>READY</em>}
              </button>
            ))}
          </div>
          <div className="immutable-card"><span>IMMUTABLE RUN SPEC</span><dl><div><dt>Scenario ID</dt><dd>scn_…8f31</dd></div><div><dt>Seed</dt><dd>wm-0713</dd></div><div><dt>Environment</dt><dd>env_a42</dd></div></dl><p>Every candidate replays this exact specification.</p></div>
          <div className="journey-mini"><span>CRITICAL JOURNEY</span><b>🛒 Complete checkout</b><div className="step-dots">{journeySteps.map((s, i) => <i key={s} className={graphState === "failed" && i > 2 ? "failed" : ""} title={s}>{i + 1}</i>)}</div><small>Playwright · 6 steps · SLO 2.0s</small></div>
        </aside>

        <section className="twin-panel panel" aria-label="Interactive system graph">
          <div className="canvas-head"><div><span className="eyebrow">LIVE SYSTEM MODEL</span><b>{phase === "ready" ? "Healthy baseline" : phase === "running" ? "Simulation in progress" : graphState === "failed" ? "Failure propagation detected" : phase === "verified" ? "Repair verified" : "Repair candidate ready"}</b></div><div className="legend"><span><i className="healthy" />Healthy</span><span><i className="degraded" />Degraded</span><span><i className="failed" />Failed</span></div></div>
          <div className={`graph ${graphState}`}>
            <div className="grid-lines" />
            <div className="edge e1"/><div className="edge e2"/><div className="edge e3"/><div className="edge e4"/><div className="edge e5"/><div className="edge e6"/>
            {nodes.map((node) => (
              <button key={node.id} data-testid={`node-${node.id}`} onClick={() => setSelectedNode(node.id)} className={`graph-node ${selectedNode === node.id ? "focused" : ""} ${isBroken(node.id) ? node.id === (scenario === "payments" ? "stripe" : scenario === "database" ? "database" : "gateway") ? "failed" : "degraded" : "healthy"}`} style={{ left: `${node.x}%`, top: `${node.y}%` }}>
                <i>{node.kind === "External" ? "↗" : node.kind === "Postgres" ? "▤" : node.kind === "Worker" ? "✦" : "◇"}</i><span><b>{node.label}</b><small>{node.kind}</small></span><em />
              </button>
            ))}
            {graphState === "failed" && <div className="impact-callout"><span>!</span><div><b>Propagation path found</b><small>{data.target} → Checkout → Orders → Customer</small></div></div>}
          </div>
          <div className="inspector" data-testid="node-inspector"><div><span>SELECTED NODE</span><b>{selected.label}</b></div><dl><div><dt>Health</dt><dd className={isBroken(selected.id) ? "danger" : "success"}>● {isBroken(selected.id) ? "Degraded" : "Healthy"}</dd></div><div><dt>P95</dt><dd>{isBroken(selected.id) ? activeMetrics.latency : "184ms"}</dd></div><div><dt>Throughput</dt><dd>1,248 rpm</dd></div><div><dt>Evidence</dt><dd>{selected.file}</dd></div></dl></div>
        </section>

        <aside className="activity-panel panel">
          <div className="panel-heading"><span>RUN TIMELINE</span><b>{phase === "ready" ? "IDLE" : phase === "verified" ? "VERIFIED" : "LIVE"}</b></div>
          <div className="run-clock"><strong>00:{String(phase === "running" ? elapsed : phase === "ready" ? 0 : 45).padStart(2, "0")}</strong><span>/ 02:00</span><div><i style={{ width: `${phase === "running" ? Math.max(elapsed * 2.2, 8) : phase === "ready" ? 0 : 42}%` }} /></div></div>
          <ol className="timeline">
            <li className={phase !== "ready" ? "done" : "active"}><time>00:00</time><div><b>Baseline captured</b><small>7 services healthy · 342ms p95</small></div></li>
            <li className={phase === "ready" ? "future" : phase === "running" ? "active" : "danger"}><time>00:15</time><div><b>{data.event}</b><small>Target: {data.target}</small></div></li>
            <li className={["failed","repairing","repaired","verified"].includes(phase) ? "danger" : "future"}><time>00:21</time><div><b>Checkout SLO breached</b><small>{data.baseline.errors} errors · {data.baseline.latency} p95</small></div></li>
            <li className={["repaired","verified"].includes(phase) ? "done" : "future"}><time>00:45</time><div><b>{phase === "verified" ? "Replay passed" : "Fault window complete"}</b><small>{phase === "verified" ? "All assertions verified" : "System recovering"}</small></div></li>
          </ol>

          {phase === "failed" && <div className="action-card danger-card"><span>FAILURE CONFIRMED</span><h3>Checkout collapses when the payment dependency stops responding.</h3><p>Worker saturation propagates to Orders. 78% of customers cannot complete checkout.</p><button data-testid="investigate-repair" onClick={startRepair}>Investigate with Codex <span>→</span></button></div>}
          {phase === "repairing" && <div className="agent-card"><span className="agent-orb">✦</span><div><b>Codex is repairing the system</b><small>Tracing failure → editing payment.ts → running checks</small><div className="agent-progress"><i /></div></div></div>}
          {(phase === "repaired" || phase === "verified") && <div className="action-card winner-card"><span>✦ CODEX REPAIR</span><h3>Graceful payment fallback</h3><p>Timeout + circuit breaker + durable retry queue. 2 files changed, +48 −6.</p><div className="patch-tags"><i>payment.ts</i><i>checkout.spec.ts</i></div>{phase === "repaired" ? <button data-testid="replay-scenario" onClick={verify}>Replay identical scenario <span>▶</span></button> : <button data-testid="view-report" onClick={() => setShowReport(true)}>View verified report <span>→</span></button>}</div>}
        </aside>
      </div>

      {phase === "verified" && <section className="verified-banner" data-testid="verified-result"><div className="verified-icon">✓</div><div><span>IDENTICAL REPLAY PASSED</span><h2>Checkout survives the failure.</h2><p>Same scenario <b>scn_checkout_20x_8f31</b> · same seed · clean environment</p></div><div className="before-after"><div><span>BEFORE</span><b>{data.baseline.errors}</b><small>error rate</small></div><em>→</em><div><span>AFTER</span><b>{data.after.errors}</b><small>error rate</small></div></div><button onClick={() => setShowReport(true)}>Open report</button><button className="pr-button" onClick={() => setShowPr(true)}>Create draft PR</button></section>}

      {showReport && <div className="modal-backdrop" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && setShowReport(false)}><section className="report-modal" role="dialog" aria-modal="true" aria-labelledby="report-title"><button className="modal-close" aria-label="Close report" onClick={() => setShowReport(false)}>×</button><div className="report-brand"><Logo /><span>WORLDMODEL / VERIFICATION</span><b>VERIFIED</b></div><h2 id="report-title">Checkout resilience report</h2><p className="report-sub">Evidence from an immutable replay · July 13, 2026</p><div className="report-score"><span>RESILIENCE SCORE</span><strong>{data.baseline.score}</strong><em>→</em><strong>{data.after.score}</strong><b>+{data.after.score - data.baseline.score}</b></div><div className="comparison-grid"><div><span>ERROR RATE</span><del>{data.baseline.errors}</del><strong>{data.after.errors}</strong></div><div><span>P95 LATENCY</span><del>{data.baseline.latency}</del><strong>{data.after.latency}</strong></div><div><span>JOURNEY SUCCESS</span><del>{data.baseline.journey}</del><strong>{data.after.journey}</strong></div></div><h3>What changed</h3><p>Codex added a 1.5s timeout, a circuit breaker, idempotent order handling, and a durable retry queue so checkout can safely accept an order while the payment provider recovers.</p><ul><li><b>6/6</b> Playwright journey steps passed</li><li><b>48/48</b> unit and integration checks passed</li><li><b>0</b> duplicate or lost orders</li></ul><div className="report-actions"><button onClick={downloadReport}>↓ Download report</button><button className="primary" onClick={() => { setShowReport(false); setShowPr(true); }}>Create draft PR →</button></div></section></div>}

      {showPr && <div className="modal-backdrop" role="presentation"><section className="pr-modal" role="dialog" aria-modal="true" aria-labelledby="pr-title"><button className="modal-close" aria-label="Close pull request" onClick={() => setShowPr(false)}>×</button><span className="github-mark">⌘</span><div className="draft-pill">DRAFT</div><h2 id="pr-title">feat: make checkout resilient to payment outages</h2><p>Prepared on <b>worldmodel/resilient-checkout</b> with the verified patch, scenario results, and rollback guidance attached.</p><div className="pr-checks"><span>✓ Simulation replay</span><span>✓ Playwright journey</span><span>✓ 48 checks</span></div><div className="pr-link"><span>shopstream/demo-store</span><b>#248</b></div><button className="primary" onClick={() => setShowPr(false)}>Draft PR ready <span>✓</span></button><small>Demo artifact — connect GitHub to publish this draft.</small></section></div>}
    </main>
  );
}
