function value(record, key, fallback = "—") {
  const result = record[key];
  return result === null || result === undefined || result === "" ? fallback : String(result);
}

export function formatVerificationReport(run) {
  const sample = run.workspace_mode === "sample";
  return `WORLDMODEL ${sample ? "SAMPLE " : ""}VERIFICATION REPORT

${sample ? "SAMPLE DATA — This prepared Northstar result is illustrative and is not evidence from a customer repository.\n" : ""}
Project: ${value(run, "project_name")}
Repository: ${value(run, "repository")} · ${value(run, "branch")}
Scenario: ${value(run, "scenario")}
Scenario fingerprint: ${value(run, "scenario_fingerprint")}
Seed: ${value(run, "seed")}
Run ID: ${value(run, "id")}
Verified: ${value(run, "verified_at")}

BEFORE → AFTER
Resilience: ${value(run, "before_score")} → ${value(run, "after_score")}
Error rate: ${value(run, "before_error_rate", value(run, "error_rate"))} → ${value(run, "after_error_rate")}
P95 latency: ${value(run, "before_latency_ms")}ms → ${value(run, "after_latency_ms")}ms
Journey success: ${value(run, "before_journey_success")}% → ${value(run, "after_journey_success")}%

VERIFICATION EVIDENCE
✓ Identical scenario fingerprint and seed replayed
✓ Complete checkout journey passed
✓ Service health returned within the release gate
✓ Repair evidence is linked to the ${sample ? "prepared sample" : "tenant-owned"} simulation record

DECISION
${sample ? "Illustrative repair candidate only. Create a clean customer workspace and rerun this scenario before making a release decision." : "Verified repair candidate is ready for human review. Merge remains a deliberate reviewer action."}

Generated by WorldModel for Software`;
}
