function value(record, key, fallback = "—") {
  const result = record[key];
  return result === null || result === undefined || result === "" ? fallback : String(result);
}

export function formatVerificationReport(run) {
  const sample = run.workspace_mode === "sample";
  const repositoryVerified = Boolean(run.repository_verified);
  const evidenceKind = run.evidence_kind || (sample ? "sample_fixture" : "modeled");
  const observed = evidenceKind === "observed";
  const reportKind = sample
    ? "SAMPLE VERIFICATION"
    : observed
      ? "VERIFICATION"
      : "MODELED REPLAY";
  const disclosures = sample
    ? "SAMPLE DATA — This prepared Northstar result is illustrative and is not evidence from a customer repository."
    : `${repositoryVerified ? "REPOSITORY OWNERSHIP — Verified through the workspace's GitHub installation." : "UNVERIFIED REPOSITORY — The repository name was entered manually and ownership has not been validated."}\n${observed ? "OBSERVED EVIDENCE — Metrics were captured from an identified virtual test environment." : "MODELED EVIDENCE — Metrics are deterministic scenario projections; no customer virtual-environment execution was observed."}`;
  const decision = sample
    ? "Illustrative repair candidate only. Create a clean customer workspace and rerun this scenario before making a release decision."
    : !observed
      ? "Modeled replay passed. Use this result for planning only; run the scenario in an instrumented virtual environment before treating it as release verification."
      : repositoryVerified
        ? "Observed repair candidate is ready for human review. Merge remains a deliberate reviewer action."
        : "Observed replay passed, but repository ownership is unverified. Import the repository through the workspace GitHub installation before treating this as tenant-owned release evidence.";
  const environmentEvidence = observed
    ? `Environment ID: ${value(run, "environment_id")}\nJourney runner: ${value(run, "journey_runner")}\nEnvironment destroyed: ${value(run, "environment_destroyed_at")}\n`
    : "";
  const serviceHealth = observed
    ? `Service health: ${value(run, "before_service_health")}% → ${value(run, "after_service_health")}%\n`
    : "";
  return `WORLDMODEL ${reportKind} REPORT

${disclosures}

Project: ${value(run, "project_name")}
Repository: ${value(run, "repository")} · ${value(run, "branch")}
Evidence kind: ${evidenceKind}
${environmentEvidence}Scenario: ${value(run, "scenario")}
Scenario fingerprint: ${value(run, "scenario_fingerprint")}
Seed: ${value(run, "seed")}
Run ID: ${value(run, "id")}
Verified: ${value(run, "verified_at")}

BEFORE → AFTER
Resilience: ${value(run, "before_score")} → ${value(run, "after_score")}
Error rate: ${value(run, "before_error_rate", value(run, "error_rate"))} → ${value(run, "after_error_rate")}
P95 latency: ${value(run, "before_latency_ms")}ms → ${value(run, "after_latency_ms")}ms
Journey success: ${value(run, "before_journey_success")}% → ${value(run, "after_journey_success")}%
${serviceHealth}

${observed || sample ? "VERIFICATION EVIDENCE" : "MODELED EVIDENCE"}
${observed || sample ? "✓" : "~"} Identical scenario fingerprint and seed replayed
${observed || sample ? "✓" : "~"} Complete checkout journey ${observed || sample ? "passed" : "projected"}
${observed || sample ? "✓" : "~"} Service health ${observed || sample ? "returned" : "projected"} within the release gate
${observed || sample ? "✓" : "~"} Repair evidence is linked to the ${sample ? "prepared sample" : repositoryVerified ? "ownership-validated tenant" : "unverified workspace"} simulation record

DECISION
${decision}

Generated by WorldModel for Software`;
}
