"use client";

import type { CSSProperties, FormEvent } from "react";
import { useCallback, useEffect, useState } from "react";
import "./dashboard.css";

type Tab = "overview" | "projects" | "runs" | "reports" | "usage" | "team" | "settings";
type Workspace = { id:string; name:string; plan:string; simulation_minutes:number; monthly_limit:number };
type Project = { id:string; name:string; repository:string; branch:string; status:string; resilience_score:number; service_count:number; updated_at:string };
type Run = { id:string; project_name:string; scenario:string; status:string; before_score:number; after_score:number|null; error_rate:string; latency_ms:number; journey_success:number; created_at:string };
type Member = { email:string; role:string; created_at:string };
type Snapshot = { workspace:Workspace; projects:Project[]; runs:Run[]; members:Member[]; user:{email:string;displayName:string} };

const navItems:Array<{id:Tab;label:string;icon:string}> = [
  {id:"overview",label:"Overview",icon:"⌂"},{id:"projects",label:"Projects",icon:"◇"},{id:"runs",label:"Simulation runs",icon:"▶"},{id:"reports",label:"Reports",icon:"▤"},{id:"usage",label:"Usage & plan",icon:"◒"},{id:"team",label:"Team",icon:"♙"},{id:"settings",label:"Settings",icon:"⚙"},
];
function Logo(){return <span className="saas-logo" aria-hidden="true"><i/><i/><i/></span>}
function statusLabel(status:string){return status==="verified"?"Verified":status==="completed"?"Needs repair":status==="scanning"?"Scanning":"Ready"}
function dateLabel(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?"Just now":date.toLocaleDateString("en-US",{month:"short",day:"numeric"})}

export default function Dashboard(){
  const [tab,setTab]=useState<Tab>("overview");
  const [data,setData]=useState<Snapshot|null>(null);
  const [error,setError]=useState("");
  const [showCreate,setShowCreate]=useState(false);
  const [showUpgrade,setShowUpgrade]=useState(false);
  const [showInvite,setShowInvite]=useState(false);
  const [creating,setCreating]=useState(false);
  const [notice,setNotice]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/saas");const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Unable to load workspace");setData(payload)},[]);
  useEffect(()=>{const controller=new AbortController();fetch("/api/saas",{signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Unable to load workspace");return payload}).then(setData).catch(reason=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"Unable to load workspace")});return()=>controller.abort()},[]);
  async function mutate(payload:Record<string,FormDataEntryValue|null>){const response=await fetch("/api/saas",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to save changes");await load();return result}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setCreating(true);setError("");const form=new FormData(event.currentTarget);try{await mutate({action:"create-project",name:form.get("name"),repository:form.get("repository"),branch:form.get("branch")});setShowCreate(false);setTab("projects")}catch(reason){setError(reason instanceof Error?reason.message:"Unable to create project")}finally{setCreating(false)}}
  async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();setCreating(true);setError("");const form=new FormData(event.currentTarget);try{await mutate({action:"invite-member",email:form.get("email"),role:form.get("role")});setShowInvite(false);setNotice("Team member added to the workspace.")}catch(reason){setError(reason instanceof Error?reason.message:"Unable to invite member")}finally{setCreating(false)}}
  async function saveWorkspace(event:FormEvent<HTMLFormElement>){event.preventDefault();setCreating(true);setError("");const form=new FormData(event.currentTarget);try{await mutate({action:"update-workspace",name:form.get("name")});setNotice("Workspace settings saved.")}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save workspace")}finally{setCreating(false)}}
  if(!data&&!error)return <main className="saas-loading"><Logo/><div/><span>Loading your workspace…</span></main>;
  if(!data)return <main className="saas-loading"><Logo/><h1>Workspace unavailable</h1><p>{error}</p><button onClick={()=>location.reload()}>Try again</button></main>;
  const verifiedRuns=data.runs.filter(run=>run.status==="verified").length;
  const usagePercent=Math.round((data.workspace.simulation_minutes/data.workspace.monthly_limit)*100);
  return <main className="saas-shell">
    <aside className="saas-sidebar"><div className="saas-brand"><Logo/><span>WorldModel</span><b>PRO</b></div><button className="workspace-switcher"><span>NE</span><div><b>{data.workspace.name}</b><small>Pro trial workspace</small></div><em>⌄</em></button><nav aria-label="Workspace navigation">{navItems.map(item=><button key={item.id} data-testid={`nav-${item.id}`} className={tab===item.id?"active":""} onClick={()=>setTab(item.id)}><i>{item.icon}</i>{item.label}{item.id==="reports"&&<em>{verifiedRuns}</em>}</button>)}</nav><div className="sidebar-bottom"><div className="trial-card"><span>PRO TRIAL · 11 DAYS LEFT</span><b>{data.workspace.simulation_minutes} of {data.workspace.monthly_limit} minutes</b><div><i style={{width:`${usagePercent}%`}}/></div><button onClick={()=>setShowUpgrade(true)}>View plans</button></div><button className="user-chip"><span>{data.user.displayName.slice(0,2).toUpperCase()}</span><div><b>{data.user.displayName}</b><small>{data.user.email}</small></div><em>•••</em></button></div></aside>
    <section className="saas-main"><header className="saas-topbar"><div><span>{data.workspace.name}</span><b>/</b><strong>{navItems.find(item=>item.id===tab)?.label}</strong></div><div><button className="icon-button" aria-label="Help">?</button><button className="icon-button" aria-label="Notifications">♢<i/></button><button className="new-project" data-testid="new-project" onClick={()=>setShowCreate(true)}>＋ New project</button></div></header><div className="saas-content">{notice&&<button className="saas-notice" onClick={()=>setNotice("")}>✓ {notice}<span>×</span></button>}
      {tab==="overview"&&<><section className="welcome-row"><div><span>MONDAY, JULY 13</span><h1>Good evening, {data.user.displayName}.</h1><p>Your software twins ran three resilience experiments this week. One verified repair is ready for review.</p></div><button onClick={()=>location.href="/"}>Run a simulation <b>→</b></button></section><section className="saas-kpis"><Kpi label="AVERAGE RESILIENCE" value="82" suffix="/100" note="↑ 12 this month"/><Kpi label="SIMULATION RUNS" value={String(data.runs.length)} note="3 this week"/><Kpi label="VERIFIED REPAIRS" value={String(verifiedRuns)} note="1 awaiting review"/><Kpi label="FAILURES CAUGHT" value="7" note="Before production"/></section><div className="overview-grid"><ProjectList projects={data.projects} onAll={()=>setTab("projects")}/><Activity/></div><div className="overview-grid bottom"><section className="saas-card"><CardHeader eyebrow="RECENT RUNS" title="Simulation history" action="View all →" onAction={()=>setTab("runs")}/><RunTable runs={data.runs.slice(0,3)}/></section><section className="saas-card readiness-card"><span>RELEASE READINESS</span><div className="readiness-score"><strong>88</strong><small>/100</small></div><h3>Ready with review</h3><p>The verified checkout repair is merge-ready. Database latency remains above your SLO.</p><button onClick={()=>setTab("reports")}>Review evidence →</button></section></div></>}
      {tab==="projects"&&<><SectionHeader eyebrow="PROJECTS" title="Software twins" description="Connect applications, review architecture models, and track resilience over time." action="New project" onAction={()=>setShowCreate(true)}/><section className="project-grid">{data.projects.map(project=><article key={project.id}><div className="project-card-top"><div className="project-icon">◇</div><span className={`saas-status ${project.status}`}>{statusLabel(project.status)}</span></div><h3>{project.name}</h3><p>⌘ {project.repository}</p><dl><div><dt>Resilience</dt><dd>{project.resilience_score||"—"}</dd></div><div><dt>Services</dt><dd>{project.service_count||"Scanning"}</dd></div><div><dt>Branch</dt><dd>{project.branch}</dd></div></dl><button onClick={()=>location.href="/"}>Open software twin →</button></article>)}<button className="add-project-card" onClick={()=>setShowCreate(true)}>＋<b>Connect another repository</b><small>GitHub, GitLab, or prepared sample</small></button></section></>}
      {tab==="runs"&&<><SectionHeader eyebrow="SIMULATIONS" title="Run history" description="Every run preserves its scenario, seed, environment, telemetry, and journey evidence." action="New simulation" onAction={()=>location.href="/"}/><section className="saas-card full-table"><RunTable runs={data.runs}/></section></>}
      {tab==="reports"&&<><SectionHeader eyebrow="REPORTS" title="Verification evidence" description="Decision-ready before-and-after proof for reviewers, pull requests, and release gates."/><section className="report-grid-saas">{data.runs.filter(run=>run.status==="verified").map(run=><article key={run.id}><span>VERIFIED REPORT</span><h3>{run.scenario}</h3><p>{run.project_name} · {dateLabel(run.created_at)}</p><div><strong>{run.before_score}</strong><em>→</em><strong>{run.after_score}</strong><b>+{(run.after_score||0)-run.before_score}</b></div><ul><li>✓ Immutable replay matched</li><li>✓ Journey success {run.journey_success}%</li><li>✓ Tenant-owned evidence</li></ul><button onClick={()=>location.href=`/api/reports?run=${encodeURIComponent(run.id)}`}>Download report ↓</button></article>)}</section></>}
      {tab==="usage"&&<><SectionHeader eyebrow="USAGE & PLAN" title="Pro trial" description="Scale resilience testing across projects and your engineering team." action="Upgrade plan" onAction={()=>setShowUpgrade(true)}/><section className="billing-grid"><article className="saas-card usage-detail"><span>SIMULATION MINUTES · JULY</span><div><strong>{data.workspace.simulation_minutes}</strong><small> / {data.workspace.monthly_limit} minutes</small></div><div className="usage-bar"><i style={{width:`${usagePercent}%`}}/></div><p>{data.workspace.monthly_limit-data.workspace.simulation_minutes} minutes remaining · resets August 1</p><div className="usage-bars">{[18,32,24,46,62,38,74,58,81,66,42,54].map((height,index)=><i key={index} style={{height:`${height}%`}}/>)}</div></article><article className="saas-card plan-card"><span>CURRENT PLAN</span><h3>Pro trial</h3><strong>$0<small> for 14 days</small></strong><ul><li>✓ 500 simulation minutes</li><li>✓ 10 private projects</li><li>✓ Codex repair generation</li><li>✓ Draft pull requests</li><li>✓ 5 team seats</li></ul><button onClick={()=>setShowUpgrade(true)}>Choose a paid plan</button></article></section></>}
      {tab==="team"&&<><SectionHeader eyebrow="TEAM" title="Workspace members" description="Collaborate on projects, simulations, and verified repair decisions." action="Invite member" onAction={()=>setShowInvite(true)}/><section className="saas-card members-table"><header><span>MEMBER</span><span>ROLE</span><span>JOINED</span><span></span></header>{data.members.map(member=><div key={member.email}><span className="member-name"><i>{member.email.slice(0,2).toUpperCase()}</i><b>{member.email}</b></span><span>{member.role}</span><span>{dateLabel(member.created_at)}</span><button>•••</button></div>)}</section></>}
      {tab==="settings"&&<><SectionHeader eyebrow="SETTINGS" title="Workspace settings" description="Manage workspace identity, security defaults, and notification preferences."/><section className="settings-grid"><form className="saas-card" onSubmit={saveWorkspace}><h3>General</h3><label>Workspace name<input name="name" required defaultValue={data.workspace.name}/></label><label>Default branch<input defaultValue="main" disabled/></label><button disabled={creating}>{creating?"Saving…":"Save changes"}</button></form><article className="saas-card"><h3>Simulation safety</h3><Toggle title="Require approval before repair" note="Human approval stays mandatory."/><Toggle title="Block outbound network" note="Mocks are used for external services."/><Toggle title="Auto-delete environments" note="Destroy after five minutes."/></article></section></>}
    </div></section>
    {showCreate&&<div className="saas-modal-backdrop"><section className="saas-modal" role="dialog" aria-modal="true" aria-labelledby="create-title"><button className="saas-modal-close" onClick={()=>setShowCreate(false)} aria-label="Close project dialog">×</button><span>NEW SOFTWARE TWIN</span><h2 id="create-title">Connect a repository</h2><p>WorldModel starts with read-only access and asks before running any code.</p><form onSubmit={create}><label>Project name<input name="name" required placeholder="Payments resilience"/></label><label>Repository<input name="repository" required placeholder="organization/repository"/></label><label>Branch<input name="branch" defaultValue="main"/></label>{error&&<p className="form-error">{error}</p>}<div><button type="button" onClick={()=>setShowCreate(false)}>Cancel</button><button className="primary" disabled={creating}>{creating?"Creating…":"Create project →"}</button></div></form></section></div>}
    {showInvite&&<div className="saas-modal-backdrop"><section className="saas-modal" role="dialog" aria-modal="true" aria-labelledby="invite-title"><button className="saas-modal-close" onClick={()=>setShowInvite(false)} aria-label="Close invite dialog">×</button><span>WORKSPACE ACCESS</span><h2 id="invite-title">Invite a team member</h2><p>Add a collaborator with the minimum role they need.</p><form onSubmit={invite}><label>Email address<input name="email" type="email" required placeholder="engineer@company.com"/></label><label>Role<select name="role" defaultValue="member"><option value="member">Member</option><option value="admin">Admin</option><option value="viewer">Viewer</option></select></label>{error&&<p className="form-error">{error}</p>}<div><button type="button" onClick={()=>setShowInvite(false)}>Cancel</button><button className="primary" disabled={creating}>{creating?"Adding…":"Add member →"}</button></div></form></section></div>}
    {showUpgrade&&<div className="saas-modal-backdrop"><section className="upgrade-modal" role="dialog" aria-modal="true" aria-labelledby="upgrade-title"><button className="saas-modal-close" onClick={()=>setShowUpgrade(false)} aria-label="Close plans">×</button><span>CHOOSE YOUR PLAN</span><h2 id="upgrade-title">Reliability before production.</h2><p>Start with a 14-day trial. No charge until you select a plan.</p><div className="plans"><Plan name="STARTER" price="49" description="For individual developers." items={["150 simulation minutes","3 projects","1 seat"]}/><Plan name="PRO" price="199" description="For startup engineering teams." items={["500 simulation minutes","10 projects","5 seats","Draft PRs + API access"]} recommended/><Plan name="BUSINESS" price="599" description="For reliability programs." items={["2,000 simulation minutes","Unlimited projects","20 seats","SSO + audit export"]}/></div><small>Checkout is intentionally disabled until Stripe products and legal terms are configured.</small></section></div>}
  </main>
}

function Kpi({label,value,suffix,note}:{label:string;value:string;suffix?:string;note:string}){return <div><span>{label}</span><strong>{value}{suffix&&<small>{suffix}</small>}</strong><em>{note}</em></div>}
function CardHeader({eyebrow,title,action,onAction}:{eyebrow:string;title:string;action?:string;onAction?:()=>void}){return <header><div><span>{eyebrow}</span><b>{title}</b></div>{action&&<button onClick={onAction}>{action}</button>}</header>}
function ProjectList({projects,onAll}:{projects:Project[];onAll:()=>void}){return <section className="saas-card projects-card"><CardHeader eyebrow="PROJECTS" title="Your software twins" action="View all →" onAction={onAll}/>{projects.map(project=><article key={project.id}><div className="project-icon">◇</div><div><b>{project.name}</b><small>⌘ {project.repository} · {project.branch}</small></div><span className={`saas-status ${project.status}`}>{statusLabel(project.status)}</span><div className="score-ring" style={{"--score":`${project.resilience_score*3.6}deg`} as CSSProperties}><b>{project.resilience_score}</b></div><button aria-label={`Open ${project.name}`} onClick={()=>location.href="/"}>→</button></article>)}</section>}
function Activity(){return <section className="saas-card activity-card"><CardHeader eyebrow="ACTIVITY" title="Recent events"/><ol><li><i className="green">✓</i><div><b>Repair verified</b><p>Payment outage survived with 100% journey success.</p><small>18 minutes ago</small></div></li><li><i className="purple">✦</i><div><b>Codex candidate ready</b><p>Graceful payment fallback · 2 files changed.</p><small>24 minutes ago</small></div></li><li><i className="red">!</i><div><b>Failure detected</b><p>Database slowdown breached checkout SLO.</p><small>Yesterday</small></div></li></ol></section>}
function SectionHeader({eyebrow,title,description,action,onAction}:{eyebrow:string;title:string;description:string;action?:string;onAction?:()=>void}){return <section className="section-header"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action&&<button onClick={onAction}>{action} <b>→</b></button>}</section>}
function RunTable({runs}:{runs:Run[]}){return <div className="run-table"><header><span>SCENARIO</span><span>STATUS</span><span>SCORE</span><span>JOURNEY</span><span>DATE</span><span></span></header>{runs.map(run=><article key={run.id}><div><i>{run.scenario.includes("Payment")?"⚡":run.scenario.includes("Database")?"▤":"↗"}</i><span><b>{run.scenario}</b><small>{run.project_name}</small></span></div><span className={`saas-status ${run.status}`}>{statusLabel(run.status)}</span><span className="run-score"><b>{run.before_score}</b>{run.after_score&&<><em>→</em><strong>{run.after_score}</strong></>}</span><span>{run.journey_success}%</span><span>{dateLabel(run.created_at)}</span><button aria-label={run.status==="verified"?`Download ${run.scenario} report`:`Open ${run.scenario}`} onClick={()=>location.href=run.status==="verified"?`/api/reports?run=${encodeURIComponent(run.id)}`:"/"}>{run.status==="verified"?"↓":"→"}</button></article>)}</div>}
function Toggle({title,note}:{title:string;note:string}){return <label className="toggle-row"><span><b>{title}</b><small>{note}</small></span><input type="checkbox" defaultChecked/></label>}
function Plan({name,price,description,items,recommended}:{name:string;price:string;description:string;items:string[];recommended?:boolean}){return <article className={recommended?"recommended":""}>{recommended&&<b>MOST POPULAR</b>}<span>{name}</span><strong>${price}<small>/month</small></strong><p>{description}</p><ul>{items.map(item=><li key={item}>✓ {item}</li>)}</ul><button>{name==="BUSINESS"?"Contact sales":`Choose ${name[0]+name.slice(1).toLowerCase()}`}</button></article>}
